"""Update Migration

Revision ID: b2e5ea405c29
Revises: 6c42eb10000b
Create Date: 2025-10-30 13:49:53.098553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2e5ea405c29'
down_revision = '6c42eb10000b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freight_trips')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('trip_type',
               existing_type=mysql.ENUM('NORMAL', 'PACKAGE', 'FREIGHT'),
               type_=sa.Enum('NORMAL', 'PACKAGE', 'CUSTOM', name='triptype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('trip_type',
               existing_type=sa.Enum('NORMAL', 'PACKAGE', 'CUSTOM', name='triptype'),
               type_=mysql.ENUM('NORMAL', 'PACKAGE', 'FREIGHT'),
               existing_nullable=False)

    op.create_table('freight_trips',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('freight_mode', mysql.ENUM('ONE_WAY', 'ROUND_TRIP'), nullable=True),
    sa.Column('capacity', mysql.FLOAT(), nullable=True),
    sa.Column('cargo_description', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['trips.id'], name=op.f('freight_trips_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
